### ISSUE TITLE
show/edit vega json

### ISSUE THREAD

**Issue by peller** [jupyter-incubator/declarativewidgets_explorer#12]
provide a widget to show and possibly edit the json passed to vega, such that the user could manually provide more detail than the UI controls allow.  Perhaps a toggle in place of the visual?

**Comment by peller** [comment]
might be fun to do something like a [3D card flip animation](https://davidwalsh.name/css-flip)

**Comment by dalogsdon** [comment]
![image](https://cloud.githubusercontent.com/assets/6362426/17385574/2b1aaeee-59a9-11e6-884f-7725a51b8d9e.png)
