### ISSUE TITLE
Element files where moved under `elements` directory breaking current notebooks and `explore` function

### ISSUE THREAD

**Issue by lbustelo** [jupyter-incubator/declarativewidgets_explorer#24]
The convention for element repos is to have the element definition at the root of the project. It is ok to have secondary elements in other folders for organization, but not common to move all under a subdirectory in the repo.

Because of this change, the link tags generater [here](https://github.com/jupyter-incubator/declarativewidgets/blob/master/kernel-python/declarativewidgets/widget_visualizations.py#L8) and in your [sample notebook](https://github.com/jupyter-incubator/declarativewidgets_explorer/blob/master/notebooks/examples/urth-viz-explorer.ipynb) are wrong.

**Comment by peller** [comment]
fixed by e85e8d5d84a8cfed706db46613ca22f94c76c230
