### ISSUE TITLE
Changing the value of an aggregation causes the chart to not render

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/declarativewidgets_explorer#30]
Add some chart. Add a groupby with an aggregation, and see that the chart renders properly. Change the column in the aggregation to a valid value, and see that the chart renders as an empty chart.

Example:
![image](https://cloud.githubusercontent.com/assets/6362426/17195439/5625232a-5423-11e6-8914-d37bfb003079.png)

**Comment by peller** [comment]
values are coming back wrapped in js `Number` wrapper objects.  Need to take another look at how to construct these objects in the dataframe type code.

**Comment by peller** [comment]
see jupyter-incubator/declarativewidgets#477

**Comment by dalogsdon** [comment]
👍
