### ISSUE TITLE
Numeric columns don't show ><≥≤ filter comparators

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/declarativewidgets_explorer#32]
Looks like it is using int|float rather than Numeric when checking types

**Comment by dalogsdon** [comment]
Once this is fixed, the comparators don't work due to a missing 'numexpr' lib. I'll see if its easy to set that up in our dev image and include in this issue.

**Comment by peller** [comment]
see also jupyter-incubator/declarativewidgets#426
