### ISSUE TITLE
How to make declarativewidgets.explore available?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/declarativewidgets_explorer#61]
https://github.com/jupyter-incubator/declarativewidgets_explorer/blob/master/README.md is far from intuitive.

I have a dashboards server + kernel gateway with https://github.com/jupyter-incubator/declarativewidgets up and running. How do I add the explorer widget?

**Comment by peller** [comment]
@jtyberg

Yes, the README needs to clarify that these are dev instructions and instead highlight the user instructions, which should be to simply pip install declarativewidgets and use the `explore` function

@dalogsdon will also update the video to reflect some simplifications in usage syntax

**Comment by rs2** [comment]
:+1:

**Comment by rs2** [comment]
@peller , @jtyberg: where can I find  declarativewidgets 0.7.0+? The latest feature branch is 0.6.x?

**Comment by peller** [comment]
@rs2 try the [releases page](https://github.com/jupyter-incubator/declarativewidgets/releases)
