### ISSUE TITLE
Add option to inject query code into new code cell

### ISSUE THREAD

**Issue by jtyberg** [jupyter-incubator/declarativewidgets_explorer#65]
Using the explorer widget to explore a dataframe is great, but users probably want to DO something with the data that results from the query that the widget executes.

One approach to allow them to do this may be to have the widget generate a code cell below the widget and inject the current incarnation of the Python/R/Scala code that is being used to generate the results the widget is displaying.  I like this because it gives the user a way to reproduce the results in the notebook.  From there they can tweak the code if desired, save it in a variable, etc.

**Comment by lbustelo** [comment]
Interesting, the only downside is that we've tried to keep the widgets unaware of the language of the kernel. We would need to have the kernel side of the `urth-core-dataframe` be what generates the code.

**Comment by jtyberg** [comment]
That makes sense.  Maybe `urth-core-dataframe` can provide an API that widgets can use to give them the code without executing it?  Reminds me of a dry run.  Hey, `urth-core-dataframe`, what would you do if I gave you these inputs?

**Comment by peller** [comment]
should this issue be moved to the declarativewidgets project?

**Comment by peller** [comment]
@lbustelo

**Comment by peller** [comment]
moved to jupyter-incubator/declarativewidgets#518
