### ISSUE TITLE
Minor styling fixes

### ISSUE THREAD

**Issue by peller** [jupyter-incubator/declarativewidgets_explorer#77]
- [x] Fix overloaded + icons (collapse and add)
- [x] Remove ripple
- [x] Multi-select menu item alignment
- [x] phantom widget under multiselect (see dark gray rect, below)
- [x] bump z-index for dropdown (see menu overlap with code editor, below)

![style](https://cloud.githubusercontent.com/assets/46139/17945895/d059c6a4-6a13-11e6-9d44-9ca2c4edc860.png)

**Comment by dalogsdon** [comment]
Looks like the solution for dropdown overlap is at the notebook level, setting the z-index of the output area to auto. The fix for that may need to occur in the declarativewidgets project rather than in this project.

**Comment by dalogsdon** [comment]
I was not able to reproduce the "phantom widget" under multiselect.

**Comment by peller** [comment]
I still see it, but happy to address separately

**Comment by peller** [comment]
"phantom widget" was actually ripple effect
