### ISSUE TITLE
Group-by menu should have a clear button

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/declarativewidgets_explorer#89]
Since group-by menu is a multi-select it can be tedious to clear it out, so we could put a clear button beside it to clear all selections.

**Comment by peller** [comment]
wondering if this should be part of the multi-select widget or on the form

**Comment by peller** [comment]
@dalogsdon just tried putting a clear button next to the multi-select, but there seems to be a problem with the selected state.  Clearing the state results in a couple of callbacks to `_update*` methods which somehow puts values back into `selected`
