### ISSUE TITLE
Vega charts won't display

### ISSUE THREAD

**Issue by Etiennepi** [jupyter-incubator/declarativewidgets_explorer#98]
Hi, I'm having issues rendering the charts from `explorer(df)`. The charts work fine when I create them manually and the table vizualisation works fine. I also get the follow traceback in the browser's console.

```
require.js?v=6da8be3…:165 Uncaught Error: Load timeout for modules: vega_embed,vega,vega_lite
http://requirejs.org/docs/errors.html#timeout
    at makeError (https://10.20.6.242:8088/user/epicard/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165:17)
    at checkLoaded (https://10.20.6.242:8088/user/epicard/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:693:23)
    at https://10.20.6.242:8088/user/epicard/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:714:25makeError @ require.js?v=6da8be3…:165checkLoaded @ require.js?v=6da8be3…:693(anonymous function) @ require.js?v=6da8be3…:714
```

**Comment by peller** [comment]
can you include a snapshot of the network panel in the debugger?  I'm wondering if there are 404s corresponding to those packages with malformed urls or any other clues.

**Comment by Etiennepi** [comment]
Sure thing, there are a few requests that seem to get blocked when I try to generate a chart for the first time.

![networktab](https://cloud.githubusercontent.com/assets/7561353/20012981/e2585ac6-a287-11e6-98c6-e245a5850ed3.png)

By the way, I don't know if it shoul matter, but I'm running this jupyter instance from a jupyterhub server running in a vm on my machine.

**Comment by peller** [comment]
Is the page getting served up as https?

**Comment by Etiennepi** [comment]
Yes it is.

**Comment by peller** [comment]
sorry for all the questions, but I'm not set up to test on https just yet.  When you say you can set them up manually just fine, can you show me the notebook cell code?

**Comment by Etiennepi** [comment]
It's no problem at all, I'm just glad to be getting help. 

What I mean is that when I run these cells:
```
%%html
<link rel="import" href="urth_components/urth-viz-bar/urth-viz-bar.html" is='urth-core-import'>
```
```
def dummyFunction():
    return df
```
```
%%html
<template is="urth-core-bind">
    <urth-core-function ref="dummyFunction"
                        result="{{df}}"
                        auto></urth-core-function>

    <center>Visits by Site</center>
    <urth-viz-bar 
                datarows='{{df.data}}'
                palette='["#4e73ac", "#bc5a54"]'
                rotatelabels="0"
                ybounds="[0]"
                columns='{{df.columns}}'>
        <urth-viz-col index="0" type="string"></urth-viz-col>
    </urth-viz-bar>
<template>
```
I get a bar graph, when I run this in the same notebook:

```
from declarativewidgets import explore
explore(visit_breakdown)
```

I get the side panel with options, I can select different chart types and table, but the only one that works is the table itself, the charts are blank.

**Comment by peller** [comment]
Right... so I know this is confusing, but we actually have two different sets of graphing widgets.  The (old) `urth-viz-bar`, area, etc. which maps to code that uses [nvd3](http://nvd3.org) and then `urth-viz-vega` which uses metadata from the [vega](https://vega.github.io/) project to build graphs.  Explore wraps the latter.  I suspect if you tried manually constructing examples with [urth-viz-vega](https://jupyter-incubator.github.io/declarativewidgets_explorer/#urth-viz-vega), you'd see the same problem.  I'll need to figure out why require is dropping the 'https' in the requests.

**Comment by peller** [comment]
another workaround might be to disable the security settings of the browser (obviously not a solution)  Exactly how to do this seems to change often.

http://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire

**Comment by Etiennepi** [comment]
Alright, I'll try disabling the security for it, see if it helps. I might try and take a look at the code as well later, see if I can figure it out as well. Thanks a lot for your help!

**Comment by peller** [comment]
aha.  https://github.com/jupyter-incubator/declarativewidgets_explorer/blob/master/urth-viz-vega.html#L98

Let me know if you can get a workaround going.  I might not be able to get to this for a while.

**Comment by Etiennepi** [comment]
Hey, quick update, I was able to work around the problem by following the instructions on this page. I'd be happy try and see if I can get an actual fix going too.
